version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        working_directory: ~/QLG
        steps:
          - checkout
          - restore_cache:
          keys:
           - v1-dependencies-{{ checksum "build.sbt" }}

           - run: cat /dev/null | sbt test:compile

           - save_cache:
               paths:
                 - ~/.m2
               key: v1-dependencies--{{ checksum "build.sbt" }}

           - run: cat /dev/null | sbt test:test