version: 2
jobs:
  build:
    working_directory: ~/QLG
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
      key: v1-dependencies-{{ checksum "build.sbt" }}

       - run: cat /dev/null | sbt test:compile

       - save_cache:
           paths:
             - ~/.m2
           key: v1-dependencies--{{ checksum "build.sbt" }}

       - run: cat /dev/null | sbt test:test